#!/usr/bin/make -f

all: download

clean:
	rm -f sf2/*

download: \
	sf2/01_piano/instrument.sf2 \
	sf2/02_piano/instrument.sf2 \
	sf2/03_egrand/instrument.sf2 \
	sf2/04_honkey/instrument.sf2 \
	sf2/05_epiano1/instrument.sf2 \
	sf2/06_epiano2/instrument.sf2 \
	sf2/07_harpsichord/instrument.sf2 \
	sf2/08_clavinet/instrument.sf2 \
	sf2/09_celesta/instrument.sf2 \
	sf2/10_glockenspiel/instrument.sf2 \
	sf2/11_music_box/instrument.sf2 \
	sf2/12_vibraphone/instrument.sf2 \
	sf2/13_marimba/instrument.sf2 \
	sf2/14_xylophone/instrument.sf2 \
	sf2/15_tubular_bells/instrument.sf2 \
	sf2/16_dulcimer/instrument.sf2 \
	sf2/17_drawbar_organ/instrument.sf2 \
	sf2/18_percussion_organ/instrument.sf2 \
	sf2/19_rock_organ/instrument.sf2 \
	sf2/20_church_organ/instrument.sf2 \
	sf2/21_reed_organ/instrument.sf2 \
	sf2/22_accordion/instrument.sf2 \
	sf2/23_harmonica/instrument.sf2 \
	sf2/24_tango_accordion/instrument.sf2 \
	sf2/25_nylon_guitar/instrument.sf2 \
	sf2/26_steel_guitar/instrument.sf2 \
	sf2/27_jazz_guitar/instrument.sf2 \
	sf2/28_clean_guitar/instrument.sf2 \
	sf2/29_muted_guitar/instrument.sf2 \
	sf2/30_overdriven_guitar/instrument.sf2 \
	sf2/31_distortion_guitar/instrument.sf2 \
	sf2/33_acoustic_bass/instrument.sf2 \
	sf2/34_electric_bass/instrument.sf2 \
	sf2/35_picked_bass/instrument.sf2 \
	sf2/37_slap_bass1/instrument.sf2 \
	sf2/38_slap_bass2/instrument.sf2 \
	sf2/39_synth_bass1/instrument.sf2 \
	sf2/40_synth_bass2/instrument.sf2 \
	sf2/41_violin/instrument.sf2 \
	sf2/42_viola/instrument.sf2 \
	sf2/43_cello/instrument.sf2 \
	sf2/44_contrabass/instrument.sf2 \
	sf2/45_tremolo_strings/instrument.sf2 \
	sf2/46_pizzicato_strings/instrument.sf2 \
	sf2/47_harp/instrument.sf2 \
	sf2/48_timpani/instrument.sf2 \
	sf2/49_string_ensemble1/instrument.sf2 \
	sf2/50_string_ensemble2/instrument.sf2 \
	sf2/51_synth_strings1/instrument.sf2 \
	sf2/52_synth_strings2/instrument.sf2 \
	sf2/53_choir_aah/instrument.sf2 \
	sf2/54_choir_ooh/instrument.sf2 \
	sf2/55_voice/instrument.sf2 \
	sf2/56_orchestra_hit/instrument.sf2 \
	sf2/57_trumpet/instrument.sf2 \
	sf2/58_trombone/instrument.sf2 \
	sf2/59_tuba/instrument.sf2 \
	sf2/60_muted_trumpet/instrument.sf2 \
	sf2/61_french_horn/instrument.sf2 \
	sf2/62_brass_section/instrument.sf2 \
	sf2/63_synth_brass1/instrument.sf2 \
	sf2/64_synth_brass2/instrument.sf2 \
	sf2/65_soprano_sax/instrument.sf2 \
	sf2/66_alto_sax/instrument.sf2 \
	sf2/67_tenor_sax/instrument.sf2 \
	sf2/68_baritone_sax/instrument.sf2 \
	sf2/69_oboe/instrument.sf2 \
	sf2/70_english_horn/instrument.sf2 \
	sf2/71_bassoon/instrument.sf2 \
	sf2/72_clarinet/instrument.sf2 \
	sf2/73_piccolo/instrument.sf2 \
	sf2/74_flute/instrument.sf2 \
	sf2/75_recorder/instrument.sf2 \
	sf2/76_pan_flute/instrument.sf2 \
	sf2/77_blown_bottle/instrument.sf2 \
	sf2/78_shakuhachi/instrument.sf2 \
	sf2/79_whistle/instrument.sf2 \
	sf2/80_ocarina/instrument.sf2 \
	sf2/81_square_synth/instrument.sf2 \
	sf2/82_sawtooth_synth/instrument.sf2 \
	sf2/83_calliope_synth/instrument.sf2 \
	sf2/84_chiff_synth/instrument.sf2 \
	sf2/85_charang_synth/instrument.sf2 \
	sf2/86_space_voice/instrument.sf2 \
	sf2/87_fifths/instrument.sf2 \
	sf2/88_bass_and_lead/instrument.sf2 \
	sf2/89_fantasia_pad/instrument.sf2 \
	sf2/90_warm_pad/instrument.sf2 \
	sf2/91_polysynth_pad/instrument.sf2 \
	sf2/92_choir_pad/instrument.sf2 \
	sf2/93_bowed_glass_pad/instrument.sf2 \
	sf2/94_metallic_pad/instrument.sf2 \
	sf2/95_halo_pad/instrument.sf2 \
	sf2/96_sweep_pad/instrument.sf2 \
	sf2/105_sitar/instrument.sf2 \
	sf2/106_banjo/instrument.sf2 \
	sf2/107_shamisen/instrument.sf2 \
	sf2/108_koto/instrument.sf2 \
	sf2/109_kalimba/instrument.sf2 \
	sf2/110_bag_pipe/instrument.sf2 \
	sf2/111_fiddle/instrument.sf2 \
	sf2/112_shanai/instrument.sf2 \
	sf2/117_taiko_drums/instrument.sf2 \
	samples/pearl_zildjians/ready.txt \
	samples/gscw/ready.txt \
	samples/ruffrider/ready.txt \
	samples/easyrider/ready.txt \
	\
	sf2/AirFont320/instrument.sf2 \
	sf2/AVL_Drumkits_Perc/instrument.sf2 \
	sf2/Black_Pearl_4A/instrument.sf2 \
	sf2/Black_Pearl_4B/instrument.sf2 \
	sf2/Black_Pearl_5/instrument.sf2 \
	sf2/Red_Zeppelin_4/instrument.sf2 \
	sf2/Red_Zeppelin_5/instrument.sf2 \
	sf2/FluidGM/instrument.sf2 \
	sf2/FluidBass/instrument.sf2 \
	sf2/FluidBrass/instrument.sf2 \
	sf2/FluidChromPerc/instrument.sf2 \
	sf2/FluidDrums/instrument.sf2 \
	sf2/FluidEnsemble/instrument.sf2 \
	sf2/FluidEthnic/instrument.sf2 \
	sf2/FluidGuitars/instrument.sf2 \
	sf2/FluidOrgans/instrument.sf2 \
	sf2/FluidPercussion/instrument.sf2 \
	sf2/FluidPianos/instrument.sf2 \
	sf2/FluidPipes/instrument.sf2 \
	sf2/FluidReeds/instrument.sf2 \
	sf2/FluidSoundFX/instrument.sf2 \
	sf2/FluidStrings/instrument.sf2 \
	sf2/FluidSynthFX/instrument.sf2 \
	sf2/FluidSynthLeads/instrument.sf2 \
	sf2/FluidSynthPads/instrument.sf2 \


sf2/01_piano/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/01_piano && \
		wget -c https://musical-artifacts.com/artifacts/2183/Casio_PX-860_Concert_Grand_Piano.zip && \
		7z x Casio_PX-860_Concert_Grand_Piano.zip && \
		mv "Casio PX-860 Concert Grand Piano.sf2" instrument.sf2)

sf2/02_piano/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/02_piano && \
		wget -c https://musical-artifacts.com/artifacts/1314/VS_Upright_Piano_lite.sf2 && \
		mv VS_Upright_Piano_lite.sf2 instrument.sf2)

sf2/03_egrand/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1812/House_Piano_4th.sf2 && \
		mv House_Piano_4th.sf2 instrument.sf2)

sf2/04_honkey/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2013/vl-tone.sf2 && \
		mv vl-tone.sf2 instrument.sf2)

sf2/05_epiano1/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/jRhodes3.tar.7z && \
		7z x jRhodes3.tar.7z && \
		7z x jRhodes3.tar && \
		mv jRhodes3/jRhodes3.sf2 instrument.sf2 && \
		rm jRhodes3.tar)

sf2/06_epiano2/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2248/FM_Piano.sf2 && \
		mv FM_Piano.sf2 instrument.sf2)

sf2/07_harpsichord/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/728/Harpsichord_Zell.sf2 && \
		mv Harpsichord_Zell.sf2 instrument.sf2)

sf2/08_clavinet/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2347/Clavinet_Lit.sf2 && \
		mv Clavinet_Lit.sf2 instrument.sf2)

sf2/09_celesta/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1859/Celesta.sf2 && \
		mv Celesta.sf2 instrument.sf2)

sf2/10_glockenspiel/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2399/Glockenspiel.sf2 && \
		mv Glockenspiel.sf2 instrument.sf2)

sf2/11_music_box/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2128/Musical_Box.sf2 && \
		mv Musical_Box.sf2 instrument.sf2)

sf2/12_vibraphone/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2346/Realistic_Vibraphone.sf2 && \
		mv Realistic_Vibraphone.sf2 instrument.sf2)

sf2/13_marimba/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2342/Latin_Marimba.sf2 && \
		mv Latin_Marimba.sf2 instrument.sf2)

sf2/14_xylophone/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1861/Xylophone.sf2 && \
		mv Xylophone.sf2 instrument.sf2)

sf2/15_tubular_bells/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1609/TUB_BELLS.sf2 && \
		mv TUB_BELLS.sf2 instrument.sf2)

sf2/16_dulcimer/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2181/JeffDulcimer_rel00.01.sf2 && \
		mv JeffDulcimer_rel00.01.sf2 instrument.sf2)

sf2/17_drawbar_organ/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2136/1-Tr_B3.sf2 && \
		mv 1-Tr_B3.sf2 instrument.sf2)

sf2/18_percussion_organ/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1638/Percussive_Organ.zip && \
		7z x Percussive_Organ.zip && \
		mv "(KRZ)Perc Organ.sf2" instrument.sf2)

sf2/19_rock_organ/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1611/LESLIE_SPK.sf2 && \
		mv LESLIE_SPK.sf2 instrument.sf2)

sf2/20_church_organ/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2152/the_real_shit_organ.sf2 && \
		mv the_real_shit_organ.sf2 instrument.sf2)

sf2/21_reed_organ/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2127/Wetthasinghe_Harmnium_GM_Ver.sf2 && \
		mv Wetthasinghe_Harmnium_GM_Ver.sf2 instrument.sf2)

sf2/22_accordion/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2193/accordGabanelli.sf2 && \
		mv accordGabanelli.sf2 instrument.sf2)

sf2/23_harmonica/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1860/Monsoons_Hohner_C_Harmonica_V2.sf2 && \
		mv Monsoons_Hohner_C_Harmonica_V2.sf2 instrument.sf2)

sf2/24_tango_accordion/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1871/Honher_Corona_II_Accordion.sf2 && \
		mv Honher_Corona_II_Accordion.sf2 instrument.sf2)

sf2/25_nylon_guitar/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2345/Requinto_de_adrian_rios.sf2 && \
		mv Requinto_de_adrian_rios.sf2 instrument.sf2)

sf2/26_steel_guitar/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2197/steel_gtr_samuel_pi_a.sf2 && \
		mv steel_gtr_samuel_pi_a.sf2 instrument.sf2)

sf2/27_jazz_guitar/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1648/KRZ_Acoustic_Guitar.zip && \
		7z x KRZ_Acoustic_Guitar.zip && \
		mv "KRZ Acoustic Guitar/Kurzweil K2000 - Acoustic Guitar.sf2" instrument.sf2)

sf2/28_clean_guitar/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2124/Fender_Stratocaster.sf2 && \
		mv Fender_Stratocaster.sf2 instrument.sf2)

sf2/29_muted_guitar/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://www.zanderjaz.com/soundfonts/guitars/Palm%20Muted%20Guitar.sf2 && \
		mv "Palm Muted Guitar.sf2" instrument.sf2)

sf2/30_overdriven_guitar/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2230/Rythm_Guitar_Metal.sf2 && \
		mv Rythm_Guitar_Metal.sf2 instrument.sf2)

sf2/31_distortion_guitar/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2068/UGK_amped.sf2 && \
		mv UGK_amped.sf2 instrument.sf2)



sf2/33_acoustic_bass/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2262/Jazz_Club_Bass.sf2 && \
		mv Jazz_Club_Bass.sf2 instrument.sf2)

sf2/34_electric_bass/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2144/FENDER_BASS.sf2 && \
		mv FENDER_BASS.sf2 instrument.sf2)

sf2/35_picked_bass/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2133/Janszen_s_Ibanez_Picked_Bass.sf2 && \
		mv Janszen_s_Ibanez_Picked_Bass.sf2 instrument.sf2)

sf2/37_slap_bass1/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1882/thunder_Blade_Slap_bass.sf2 && \
		mv thunder_Blade_Slap_bass.sf2 instrument.sf2)

sf2/38_slap_bass2/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/627/Billy_bass.sf2 && \
		mv Billy_bass.sf2 instrument.sf2)

sf2/39_synth_bass1/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1650/Magic_Fly_Synth.sf2 && \
		mv Magic_Fly_Synth.sf2 instrument.sf2)

sf2/40_synth_bass2/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1651/Moog_Bass.sf2 && \
		mv Moog_Bass.sf2 instrument.sf2)

sf2/41_violin/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1796/Valiant_Violin_V2.sf2 && \
		mv Valiant_Violin_V2.sf2 instrument.sf2)

sf2/42_viola/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/390/040_Florestan_String_Quartet.sf2 && \
		mv 040_Florestan_String_Quartet.sf2 instrument.sf2)

sf2/43_cello/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		cp ../42_viola/instrument.sf2 instrument.sf2)

sf2/44_contrabass/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2110/meatlof_contrabass.sf2 && \
		mv meatlof_contrabass.sf2 instrument.sf2)

sf2/45_tremolo_strings/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2125/Cruel_Tremolo_String.sf2 && \
		mv Cruel_Tremolo_String.sf2 instrument.sf2)

sf2/46_pizzicato_strings/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2113/Monumental_Pizzicato.sf2 && \
		mv Monumental_Pizzicato.sf2 instrument.sf2)

sf2/47_harp/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2109/SuperHarp.sf2 && \
		mv SuperHarp.sf2 instrument.sf2)

sf2/48_timpani/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2111/Douglas_Concert_Timpani.sf2 && \
		mv Douglas_Concert_Timpani.sf2 instrument.sf2)

sf2/49_string_ensemble1/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1764/Slow_String_Section_V2.sf2 && \
		mv Slow_String_Section_V2.sf2 instrument.sf2)

sf2/50_string_ensemble2/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1654/Full_Strings.sf2 && \
		mv Full_Strings.sf2 instrument.sf2)

sf2/51_synth_strings1/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1647/AKAI_S-Series_Strings.sf2 && \
		mv AKAI_S-Series_Strings.sf2 instrument.sf2)

sf2/52_synth_strings2/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1545/MTK_Strings_WIP.sf2 && \
		mv MTK_Strings_WIP.sf2 instrument.sf2)

sf2/53_choir_aah/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/388/052_Florestan_Ahh_Choir.sf2 && \
		mv 052_Florestan_Ahh_Choir.sf2 instrument.sf2)

sf2/54_choir_ooh/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/387/KBH_Real_and_Swell_Choir.sf2 && \
		mv KBH_Real_and_Swell_Choir.sf2 instrument.sf2)

sf2/55_voice/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/632/Milton_Voice.sf2 && \
		mv Milton_Voice.sf2 instrument.sf2)

sf2/56_orchestra_hit/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://rkhive.com/rk-download/orchhit/classhit.zip && \
		7z x classhit.zip && \
		mv Classhit.sf2 instrument.sf2)

sf2/57_trumpet/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2192/trompeta_de_adrian_rios_extreme_2.sf2 && \
		mv trompeta_de_adrian_rios_extreme_2.sf2 instrument.sf2)

sf2/58_trombone/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1768/Sinaloa_Brass_Ensemble.sf2 && \
		mv Sinaloa_Brass_Ensemble.sf2 instrument.sf2)

sf2/59_tuba/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/419/tuba.sf2 && \
		mv tuba.sf2 instrument.sf2)

sf2/60_muted_trumpet/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1163/Free_Classical_Soundfonts.zip && \
		7z x Free_Classical_Soundfonts.zip && \
		mv 13trombon_mtd.sf2 instrument.sf2)

sf2/61_french_horn/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/392/060_Florestan_French_Horns.sf2 && \
		mv 060_Florestan_French_Horns.sf2 instrument.sf2)

sf2/62_brass_section/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1768/Sinaloa_Brass_Ensemble.sf2 && \
		mv Sinaloa_Brass_Ensemble.sf2 instrument.sf2)

sf2/63_synth_brass1/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/915/Synth_Brass_1.sf2 && \
		mv Synth_Brass_1.sf2 instrument.sf2)

sf2/64_synth_brass2/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://freepats.zenvoid.org/Synthesizer/SynthBrass2/SynthBrass2-SF2-20190814.7z && \
		7z x SynthBrass2-SF2-20190814.7z && \
		mv SynthBrass2-SF2-20190814/SynthBrass2-20190814.sf2 instrument.sf2)

sf2/65_soprano_sax/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2123/SAX_SOPRANO.sf2 && \
		mv SAX_SOPRANO.sf2 instrument.sf2)

sf2/66_alto_sax/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2170/Alto_Sax_Soft.sf2 && \
		mv Alto_Sax_Soft.sf2 instrument.sf2)

sf2/67_tenor_sax/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2122/ericfontainejazz-saxophone-samples.sf2 && \
		mv ericfontainejazz-saxophone-samples.sf2 instrument.sf2)

sf2/68_baritone_sax/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/697/Baritone_Saxophone_EXS.zip && \
		7z x Baritone_Saxophone_EXS.zip && \
		mv "Baritone Saxophone EXS/Baritone Saxophone.exs" instrument.sf2)

sf2/69_oboe/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c http://beats.codenamehippie.com/samples/SoundFrontz/Oboe.sf2 && \
		mv Oboe.sf2 instrument.sf2)

sf2/70_english_horn/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2149/English_Horn_Sonatina.sf2 && \
		mv English_Horn_Sonatina.sf2 instrument.sf2)

sf2/71_bassoon/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/441/styvell-basson.sf2 && \
		mv styvell-basson.sf2 instrument.sf2)

sf2/72_clarinet/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2135/mcb.sf2 && \
		mv mcb.sf2 instrument.sf2)

sf2/73_piccolo/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2148/piccolo_flue.sf2 && \
		mv piccolo_flue.sf2 instrument.sf2)

sf2/74_flute/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/377/Transverse_Flute.sf2 && \
		mv Transverse_Flute.sf2 instrument.sf2)

sf2/75_recorder/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1801/elementary_recorder.sf2 && \
		mv elementary_recorder.sf2 instrument.sf2)

sf2/76_pan_flute/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1802/Zampo_a_V1.sf2 && \
		mv Zampo_a_V1.sf2 instrument.sf2)

sf2/77_blown_bottle/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2187/Bottle_Blow_Stereo.sf2 && \
		mv Bottle_Blow_Stereo.sf2 instrument.sf2)

sf2/78_shakuhachi/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2150/Shakuhachi_Sustained.sf2 && \
		mv Shakuhachi_Sustained.sf2 instrument.sf2)

sf2/79_whistle/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1800/whistlering.sf2 && \
		mv whistlering.sf2 instrument.sf2)

sf2/80_ocarina/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2151/azteka_2_.sf2 && \
		mv azteka_2_.sf2 instrument.sf2)

sf2/81_square_synth/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1797/Lady_Gaga_Square_Lead_V2.sf2 && \
		mv Lady_Gaga_Square_Lead_V2.sf2 instrument.sf2)

sf2/82_sawtooth_synth/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1092/saw8detune.sf2 && \
		mv saw8detune.sf2 instrument.sf2)

sf2/83_calliope_synth/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2438/Trance_Synth.sf2 && \
		mv Trance_Synth.sf2 instrument.sf2)

sf2/84_chiff_synth/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2406/Iconic_EDM_Leads.sf2 && \
		mv Iconic_EDM_Leads.sf2 instrument.sf2)

sf2/85_charang_synth/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2303/FM_Synthesis_v2.sf2 && \
		mv FM_Synthesis_v2.sf2 instrument.sf2)

sf2/86_space_voice/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2294/nothing.sf2 && \
		mv nothing.sf2 instrument.sf2)

sf2/87_fifths/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2004/3xoscSynths.sf2 && \
		mv 3xoscSynths.sf2 instrument.sf2)

sf2/88_bass_and_lead/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1852/ayako_lead.sf2 && \
		mv ayako_lead.sf2 instrument.sf2)

sf2/89_fantasia_pad/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c http://www.ibiblio.org/thammer/HammerSound/localfiles/soundfonts/hs_pt1.zip && \
		7z x hs_pt1.zip && \
		mv "HS Pads and Textures I.sf2" instrument.sf2)

sf2/90_warm_pad/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		ln -s ../89_fantasia_pad/instrument.sf2 .)

sf2/91_polysynth_pad/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c http://www.ibiblio.org/thammer/HammerSound/localfiles/soundfonts/hs_pt2.zip && \
		7z x hs_pt2.zip && \
		mv "HS Pads and Textures II.sf2" instrument.sf2)

sf2/92_choir_pad/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		ln -s ../91_polysynth_pad/instrument.sf2 .)

sf2/93_bowed_glass_pad/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		ln -s ../91_polysynth_pad/instrument.sf2 .)

sf2/94_metallic_pad/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		ln -s ../91_polysynth_pad/instrument.sf2 .)

sf2/95_halo_pad/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		ln -s ../89_fantasia_pad/instrument.sf2 .)

sf2/96_sweep_pad/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		ln -s ../89_fantasia_pad/instrument.sf2 .)





sf2/105_sitar/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2131/Realistic_Sitar_GM.sf2 && \
		mv Realistic_Sitar_GM.sf2 instrument.sf2)

sf2/106_banjo/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/890/Bubsy.sf2 && \
		mv Bubsy.sf2 instrument.sf2)

sf2/107_shamisen/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1878/Japan_Herentals.sf2 && \
		mv Japan_Herentals.sf2 instrument.sf2)

sf2/108_koto/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		ln -s ../107_shamisen/instrument.sf2 .)

sf2/109_kalimba/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2186/Kalimba.sf2 && \
		mv Kalimba.sf2 instrument.sf2)

sf2/110_bag_pipe/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2221/the_real_bagpipe.sf2 && \
		mv the_real_bagpipe.sf2 instrument.sf2)

sf2/111_fiddle/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1419/Bubsy.sf2 && \
		mv Bubsy.sf2 instrument.sf2)

sf2/112_shanai/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/2349/sinars_shanai.sf2 && \
		mv sinars_shanai.sf2 instrument.sf2)



sf2/117_taiko_drums/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://musical-artifacts.com/artifacts/1873/supremetaiko.sf2 && \
		mv supremetaiko.sf2 instrument.sf2)

samples/pearl_zildjians/ready.txt:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c https://web.archive.org/web/20100726154028/http://www.rhythminmind.net/Samples/raw%20samples%20-%20pearl%20master%20custom%20with%20zildjians.zip && \
		7z x "raw samples - pearl master custom with zildjians.zip" && \
		touch ready.txt)

samples/gscw/ready.txt:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		git clone https://github.com/gregharvey/drum-samples && \
		touch ready.txt)

samples/ruffrider/ready.txt:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c http://www.michaelkingston.fi/kingstondrums/kits/ruffrider.rar && \
		7z x "ruffrider.rar" && \
		touch ready.txt)

samples/easyrider/ready.txt:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c http://www.michaelkingston.fi/kingstondrums/kits/easyrider.rar && \
		7z x "easyrider.rar" && \
		touch ready.txt)

samples/mdk_kit/ready.txt:
	-@mkdir -p $(shell dirname $@)
	(cd $(shell dirname $@) && \
		wget -c http://download.linuxaudio.org/lau/drum_soundfonts/mdk_kit.tar.bz2 && \
		tar xf mdk_kit.tar.bz2 && \
		touch ready.txt)














sf2/AirFont320/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/AirFont320 && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/airfont_a340u.tar.7z && \
		7z x airfont_a340u.tar.7z && \
		7z x airfont_a340u.tar && \
		mv airfont_a340u/* . && \
		mv airfont_a320u.sf2 instrument.sf2 && \
		mv readme README && \
		rmdir airfont_a340u)

sf2/AVL_Drumkits_Perc/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/AVL_Drumkits_Perc && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/AVL-Drumkits-1.1-SF2-splitted/AVL_Drumkits_Perc_1.1.tar.7z && \
		7z x AVL_Drumkits_Perc_1.1.tar.7z && \
		7z x AVL_Drumkits_Perc_1.1.tar && \
		mv AVL_Drumkits_Perc_1.1/* . && \
		mv AVL_Drumkits_Perc_1.1.sf2 instrument.sf2 && \
		mv 'AVL-Drumkits CC-BY-SA License.pdf' License.pdf && \
		rmdir AVL_Drumkits_Perc_1.1)

sf2/Black_Pearl_4A/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/Black_Pearl_4A && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/AVL-Drumkits-1.1-SF2-splitted/Black_Pearl_4A-1.1.tar.7z && \
		7z x Black_Pearl_4A-1.1.tar.7z && \
		7z x Black_Pearl_4A-1.1.tar && \
		mv Black_Pearl_4A-1.1/* . && \
		mv Black_Pearl_4A-1.1.sf2 instrument.sf2 && \
		mv 'AVL-Drumkits CC-BY-SA License.pdf' License.pdf && \
		rmdir Black_Pearl_4A-1.1)

sf2/Black_Pearl_4B/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/Black_Pearl_4B && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/AVL-Drumkits-1.1-SF2-splitted/Black_Pearl_4B-1.1.tar.7z && \
		7z x Black_Pearl_4B-1.1.tar.7z && \
		7z x Black_Pearl_4B-1.1.tar && \
		mv Black_Pearl_4B-1.1/* . && \
		mv Black_Pearl_4B-1.1.sf2 instrument.sf2 && \
		mv 'AVL-Drumkits CC-BY-SA License.pdf' License.pdf && \
		rmdir Black_Pearl_4B-1.1)

sf2/Black_Pearl_5/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/Black_Pearl_5 && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/AVL-Drumkits-1.1-SF2-splitted/Black_Pearl_5-1.1.tar.7z && \
		7z x Black_Pearl_5-1.1.tar.7z && \
		7z x Black_Pearl_5-1.1.tar && \
		mv Black_Pearl_5-1.1/* . && \
		mv Black_Pearl_5-1.1.sf2 instrument.sf2 && \
		mv 'AVL-Drumkits CC-BY-SA License.pdf' License.pdf && \
		rmdir Black_Pearl_5-1.1)

sf2/Red_Zeppelin_4/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/Red_Zeppelin_4 && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/AVL-Drumkits-1.1-SF2-splitted/Red_Zeppelin_4-1.1.tar.7z && \
		7z x Red_Zeppelin_4-1.1.tar.7z && \
		7z x Red_Zeppelin_4-1.1.tar && \
		mv Red_Zeppelin_4-1.1/* . && \
		mv Red_Zeppelin_4-1.1.sf2 instrument.sf2 && \
		mv 'AVL-Drumkits CC-BY-SA License.pdf' License.pdf && \
		rmdir Red_Zeppelin_4-1.1)

sf2/Red_Zeppelin_5/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/Red_Zeppelin_5 && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/AVL-Drumkits-1.1-SF2-splitted/Red_Zeppelin_5-1.1.tar.7z && \
		7z x Red_Zeppelin_5-1.1.tar.7z && \
		7z x Red_Zeppelin_5-1.1.tar && \
		mv Red_Zeppelin_5-1.1/* . && \
		mv Red_Zeppelin_5-1.1.sf2 instrument.sf2 && \
		mv 'AVL-Drumkits CC-BY-SA License.pdf' License.pdf && \
		rmdir Red_Zeppelin_5-1.1)

sf2/FluidGM/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidGM && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3.tar.7z && \
		7z x fluidr3.tar.7z && \
		7z x fluidr3.tar && \
		mv fluidr3/* . && \
		mv fluidr3gm.sf2 instrument.sf2 && \
		mv readme README && \
		rmdir fluidr3)

sf2/FluidBass/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidBass && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_bass.sf2.tar.7z && \
		7z x fluidr3gm_bass.sf2.tar.7z && \
		7z x fluidr3gm_bass.sf2.tar && \
		mv fluidr3gm_bass.sf2 instrument.sf2)

sf2/FluidBrass/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidBrass && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_brass.sf2.tar.7z && \
		7z x fluidr3gm_brass.sf2.tar.7z && \
		7z x fluidr3gm_brass.sf2.tar && \
		mv fluidr3gm_brass.sf2 instrument.sf2)

sf2/FluidChromPerc/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidChromPerc && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_chromaticpercussion.sf2.tar.7z && \
		7z x fluidr3gm_chromaticpercussion.sf2.tar.7z && \
		7z x fluidr3gm_chromaticpercussion.sf2.tar && \
		mv fluidr3gm_chromaticpercussion.sf2 instrument.sf2)

sf2/FluidDrums/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidDrums && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_drums.sf2.tar.7z && \
		7z x fluidr3gm_drums.sf2.tar.7z && \
		7z x fluidr3gm_drums.sf2.tar && \
		mv fluidr3gm_drums.sf2 instrument.sf2)

sf2/FluidEnsemble/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidEnsemble && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_ensemble.sf2.tar.7z && \
		7z x fluidr3gm_ensemble.sf2.tar.7z && \
		7z x fluidr3gm_ensemble.sf2.tar && \
		mv fluidr3gm_ensemble.sf2 instrument.sf2)

sf2/FluidEthnic/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidEthnic && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_ethnic.sf2.tar.7z && \
		7z x fluidr3gm_ethnic.sf2.tar.7z && \
		7z x fluidr3gm_ethnic.sf2.tar && \
		mv fluidr3gm_ethnic.sf2 instrument.sf2)

sf2/FluidGuitars/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidGuitars && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_guitar.sf2.tar.7z && \
		7z x fluidr3gm_guitar.sf2.tar.7z && \
		7z x fluidr3gm_guitar.sf2.tar && \
		mv fluidr3gm_guitar.sf2 instrument.sf2)

sf2/FluidOrgans/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidOrgans && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_organ.sf2.tar.7z && \
		7z x fluidr3gm_organ.sf2.tar.7z && \
		7z x fluidr3gm_organ.sf2.tar && \
		mv fluidr3gm_organ.sf2 instrument.sf2)

sf2/FluidPercussion/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidPercussion && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_percussive.sf2.tar.7z && \
		7z x fluidr3gm_percussive.sf2.tar.7z && \
		7z x fluidr3gm_percussive.sf2.tar && \
		mv fluidr3gm_percussive.sf2 instrument.sf2)

sf2/FluidPianos/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidPianos && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_piano.sf2.tar.7z && \
		7z x fluidr3gm_piano.sf2.tar.7z && \
		7z x fluidr3gm_piano.sf2.tar && \
		mv fluidr3gm_piano.sf2 instrument.sf2)

sf2/FluidPipes/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidPipes && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_pipe.sf2.tar.7z && \
		7z x fluidr3gm_pipe.sf2.tar.7z && \
		7z x fluidr3gm_pipe.sf2.tar && \
		mv fluidr3gm_pipe.sf2 instrument.sf2)

sf2/FluidReeds/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidReeds && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_reed.sf2.tar.7z && \
		7z x fluidr3gm_reed.sf2.tar.7z && \
		7z x fluidr3gm_reed.sf2.tar && \
		mv fluidr3gm_reed.sf2 instrument.sf2)

sf2/FluidSoundFX/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidSoundFX && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_soundeffects.sf2.tar.7z && \
		7z x fluidr3gm_soundeffects.sf2.tar.7z && \
		7z x fluidr3gm_soundeffects.sf2.tar && \
		mv fluidr3gm_soundeffects.sf2 instrument.sf2)

sf2/FluidStrings/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidStrings && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_strings.sf2.tar.7z && \
		7z x fluidr3gm_strings.sf2.tar.7z && \
		7z x fluidr3gm_strings.sf2.tar && \
		mv fluidr3gm_strings.sf2 instrument.sf2)

sf2/FluidSynthFX/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidSynthFX && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_syntheffects.sf2.tar.7z && \
		7z x fluidr3gm_syntheffects.sf2.tar.7z && \
		7z x fluidr3gm_syntheffects.sf2.tar && \
		mv fluidr3gm_syntheffects.sf2 instrument.sf2)

sf2/FluidSynthLeads/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidSynthLeads && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_synthlead.sf2.tar.7z && \
		7z x fluidr3gm_synthlead.sf2.tar.7z && \
		7z x fluidr3gm_synthlead.sf2.tar && \
		mv fluidr3gm_synthlead.sf2 instrument.sf2)

sf2/FluidSynthPads/instrument.sf2:
	-@mkdir -p $(shell dirname $@)
	(cd sf2/FluidSynthPads && \
		wget -c http://download.linuxaudio.org/musical-instrument-libraries/sf2/fluidr3-splitted/fluidr3gm_synthpad.sf2.tar.7z && \
		7z x fluidr3gm_synthpad.sf2.tar.7z && \
		7z x fluidr3gm_synthpad.sf2.tar && \
		mv fluidr3gm_synthpad.sf2 instrument.sf2)
