#ifndef _SerialMach_Generated_h_
#define _SerialMach_Generated_h_

// This file is generated. Do not modify this file.

namespace TS {

namespace Serial {

#define ATOM_TYPE_LIST \
	ATOM_TYPE(CENTER_CUSTOMER) \
	ATOM_TYPE(TEST_REALTIME_SRC) \
	ATOM_TYPE(TEST_REALTIME_SINK) \
	ATOM_TYPE(TEST_POLLER_SINK) \
	ATOM_TYPE(AUDIO_HARDWARE_SINK) \
	ATOM_TYPE(AUDIO_DECODER_SRC) \
	ATOM_TYPE(AUDIO_DBG_SRC) \
	ATOM_TYPE(AUDIO_SPLITTER) \
	ATOM_TYPE(AUDIO_SPLITTER_USER) \
	ATOM_TYPE(AUDIO_JOINER) \
	ATOM_TYPE(AUDIO_JOINER_USER) \
	ATOM_TYPE(AUDIO_JOINER2_USER) \
	ATOM_TYPE(SDL_CONTEXT_ATOM) \
	ATOM_TYPE(SDL_EVENT_ATOM_PIPE) \
	ATOM_TYPE(EVENT_STATE_PIPE) \
	ATOM_TYPE(SDL_EVENT_ATOM) \
	ATOM_TYPE(EVENT_STATE) \
	ATOM_TYPE(TEST_EVENT_SRC_PIPE) \
	ATOM_TYPE(SDL_AUDIO_ATOM) \


#define ATOM_CLASS_LIST \
	ATOM_CLASS(CenterCustomer) \
	ATOM_CLASS(TestRealtimeSrc) \
	ATOM_CLASS(TestRealtimeSink) \
	ATOM_CLASS(TestPollerSink) \
	ATOM_CLASS(AudioHardwareSink) \
	ATOM_CLASS(AudioDecoderSrc) \
	ATOM_CLASS(AudioDbgSrc) \
	ATOM_CLASS(AudioSplitter) \
	ATOM_CLASS(AudioSplitterUser) \
	ATOM_CLASS(AudioJoiner) \
	ATOM_CLASS(AudioJoinerUser) \
	ATOM_CLASS(AudioJoiner2User) \
	ATOM_CLASS(SdlContextAtom) \
	ATOM_CLASS(SdlEventAtomPipe) \
	ATOM_CLASS(EventStatePipe) \
	ATOM_CLASS(SdlEventAtom) \
	ATOM_CLASS(EventState) \
	ATOM_CLASS(TestEventSrcPipe) \
	ATOM_CLASS(SdlAudioAtom) \


#define GUI_ATOM_TYPE_LIST \
	ATOM_TYPE(VIDEO_DBG_SRC) \
	ATOM_TYPE(OGL_CUSTOMER) \
	ATOM_TYPE(SDL_FBO_ATOM_S_A) \
	ATOM_TYPE(SDL_FBO_ATOM) \
	ATOM_TYPE(SDL_FBO_PIPE) \
	ATOM_TYPE(SDL_VIDEO_ATOM) \
	ATOM_TYPE(OGL_SHADER_PIPE) \
	ATOM_TYPE(OGL_SHADER_ATOM) \


#define GUI_ATOM_CLASS_LIST \
	ATOM_CLASS(VideoDbgSrc) \
	ATOM_CLASS(OglCustomer) \
	ATOM_CLASS(SdlFboAtomSA) \
	ATOM_CLASS(SdlFboAtom) \
	ATOM_CLASS(SdlFboPipe) \
	ATOM_CLASS(SdlVideoAtom) \
	ATOM_CLASS(OglShaderPipe) \
	ATOM_CLASS(OglShaderAtom) \


}

}



#endif
