
BASE(CustomerBase)
BASE_ACTION(CustomerBase,			loop.connected)

BASE(RollingValueBase)
BASE(VoidSinkBase)
BASE(VoidPollerSinkBase)
BASE(PortaudioSink)
BASE(FfmpegAtomBase)
BASE(AudioGenBase)
BASE(SplitterBase)
BASE(JoinerBase)
BASE(VideoGenBase)
BASE(OpenCVBase)
BASE(OglVideoGenBase)
BASE(SDL2ContextBase)
BASE(SDL2EventsBase)
BASE(SDL2ScreenBase)
BASE(SDL2SwScreenBase)
BASE(SDL2AudioOutputBase)
BASE(SDL2ImageBase)
BASE(OglShaderBase)
BASE(EventStateBase)
BASE(TestEventSrcBase)
BASE(OglTextureBase)
BASE(OglFboReaderBase)
BASE(VideoLoaderBase)
BASE(VolumeLoaderBase)
BASE(OglKeyboardBase)
BASE(OglAudioBase)

//BASE_FLAG(SDL2ContextBase,			forward)
//BASE_ACTION(CenterSinkSync,			center.audio.sink)
//BASE2(ReceiptOrder,				CenterReceipt,	CenterOrder)
//BASE3(CenterOglMidiSink,		OglOrder,		SinkCenterMidi,		OglMidi)
