TABLE_(USER)
	INT_			(USER_ID)		PRIMARY_KEY AUTO_INCREMENT
	STRING_			(USER_NAME, 255)
	STRING_			(USER_REAL_NAME, 255)
	TINYBLOB_		(USER_PASSWORD)
	TINYBLOB_		(USER_NEWPASSWORD)
	TIME_			(USER_NEWPASS_TIME)
	STRING_			(USER_EMAIL, 128)	DUAL_UNIQUE(USER_NAME, USER_EMAIL)
	TIME_			(USER_TOUCHED)
	STRING_			(USER_TOKEN, 32)
	TIME_			(USER_EMAIL_AUTHENTICATED)
	BINARY_			(USER_EMAIL_TOKEN, 32)
	TIME_			(USER_EMAIL_TOKEN_EXPIRES)
	TIME_			(USER_REGISTRATION)
	INT_			(USER_EDITCOUNT)
	TIME_			(USER_PASSWORD_EXPIRES)
END_TABLE

TABLE_(USER_PROPERTIES)
	INT_			(UP_USER)			REFERENCES_(USER, USER_ID)
	STRING_			(UP_PROPERTY, 255)	DUAL_UNIQUE(UP_USER, UP_PROPERTY)
	BLOB_			(UP_VALUE)
END_TABLE

TABLE_(USER_GROUPS)
	INT_			(UG_USER)			REFERENCES_(USER, USER_ID)
	STRING_			(UG_GROUP, 255)		DUAL_UNIQUE(UG_USER, UG_GROUP)
END_TABLE

TABLE_(USER_FORMER_GROUPS)
	INT_			(UFG_USER)			REFERENCES_(USER, USER_ID)
	STRING_			(UFG_GROUP, 255)	DUAL_UNIQUE(UFG_USER, UFG_GROUP)
END_TABLE

TABLE_(USER_NEWTALK)
	INT_			(UNT_ID)		REFERENCES_(USER, USER_ID)
	TIME_			(UNT_LAST_TIMESTAMP)
END_TABLE

TABLE_(LOGGING)
	INT64_			(LOG_ID)		PRIMARY_KEY AUTO_INCREMENT
	STRING_			(LOG_TYPE, 32)
	STRING_			(LOG_ACTION, 32)
	TIME_			(LOG_TIMESTAMP_)
	INT_			(LOG_USER_)		REFERENCES_(USER, USER_ID)
	STRING_			(LOG_USER_TEXT, 255)
	INT_			(LOG_NAMESPACE)
	INT_			(LOG_HUB)		REFERENCES_(HUB, HUB_ID)
	STRING_			(LOG_TITLE, 255)
	INT_			(LOG_PAGE)
	STRING_			(LOG_COMMENT, 767)
	BLOB_			(LOG_PARAMS)
	TINYINT_		(LOG_DELETED)
END_TABLE

TABLE_(VALID_TAG)
	STRING_			(VT_TAG, 255)	UNIQUE
END_TABLE

TABLE_(RECENTCHANGES)
	INT64_			(RC_ID)			PRIMARY_KEY AUTO_INCREMENT
	TIME_			(RC_TIMESTAMP)
	INT_			(RC_USER)		REFERENCES_(USER, USER_ID)
	STRING_			(RC_USER_TEXT, 255)
	INT_			(RC_NAMESPACE)
	INT_			(RC_HUB)		REFERENCES_(HUB, HUB_ID)
	STRING_			(RC_TITLE, 255)
	STRING_			(RC_COMMENT, 767)
	TINYINT_		(RC_MINOR)
	TINYINT_		(RC_BOT)
	TINYINT_		(RC_NEW)
	INT_			(RC_CUR_ID)
	INT64_			(RC_THIS_REVID)	REFERENCES_(REVISION, REV_ID)
	INT_			(RC_LAST_REVID)
	STRING_			(RC_SOURCE, 16)
	TINYINT_		(RC_PATROLLED)
	STRING_			(RC_IP, 40)
	INT_			(RC_OLD_LEN)
	INT_			(RC_NEW_LEN)
	TINYINT_		(RC_DELETED)
	INT64_			(RC_LOGID)		REFERENCES_(LOGGING, LOG_ID)
	STRING_			(RC_LOG_TYPE, 255)
	STRING_			(RC_LOG_ACTION, 255)
	BLOB_			(RC_LOG_PARAMS)
END_TABLE

TABLE_(WATCHLIST)
	INT64_			(WL_ID)			PRIMARY_KEY AUTO_INCREMENT
	INT_			(WL_USER)
	INT_			(WL_PAGE)
	INT_			(WL_NAMESPACE)
	INT_			(WL_HUB)		REFERENCES_(HUB, HUB_ID)
	STRING_			(WL_TITLE, 255)
	TIME_			(WL_NOTIFICATION_TIMESTAMP)
END_TABLE

TABLE_(HUB)
	INT_			(HUB_ID)				PRIMARY_KEY AUTO_INCREMENT
	STRING_			(HUB_TITLE, 255)
	TIME_			(HUB_CREATED)
	INT_			(HUB_CREATED_USER)		REFERENCES_(USER, USER_ID)
	STRING_			(HUB_LANG, 35)			DUAL_UNIQUE(HUB_TITLE, HUB_LANG)
	TINYINT_		(HUB_DELETED)
	TIME_			(HUB_DELETED_TIMESTAMP)
	INT_			(HUB_DELETED_USER)		REFERENCES_(USER, USER_ID)
	STRING_			(HUB_DELETED_REASON, 767)
END_TABLE

TABLE_(ARCHIVE)
	INT_			(AR_ID)				PRIMARY_KEY AUTO_INCREMENT
	INT_			(AR_NAMESPACE)
	INT_			(AR_HUB)			REFERENCES_(HUB, HUB_ID)
	STRING_			(AR_TITLE, 255)
	STRING_			(AR_COMMENT, 767)
	INT_			(AR_USER)			REFERENCES_(USER, USER_ID)
	STRING_			(AR_USER_TEXT, 255)
	TIME_			(AR_REV_TIMESTAMP)
	INT64_			(AR_REV_ID)			REFERENCES_(REVISION, REV_ID)
	INT64_			(AR_TEXT_ID)
	TINYINT_		(AR_DELETED)
	INT_			(AR_LEN)
	INT_			(AR_PAGE_ID)
	STRING_			(AR_MD5, 32)
	STRING_			(AR_CONTENT_MODEL, 32)
	STRING_			(AR_CONTENT_FORMAT, 64)
END_TABLE

TABLE_(REVISION)
	INT64_			(REV_ID)			PRIMARY_KEY AUTO_INCREMENT
	INT_			(REV_PAGE)
	INT64_			(REV_TEXT_ID)
	STRING_			(REV_COMMENT, 767)
	INT_			(REV_USER)			REFERENCES_(USER, USER_ID)
	STRING_			(REV_USER_TEXT, 255)
	TIME_			(REV_TIMESTAMP)
	TINYINT_		(REV_MINOR_EDIT)
	TINYINT_		(REV_DELETED)
	INT_			(REV_LEN)
	INT_			(REV_PARENT_ID)
	STRING_			(REV_MD5, 32)
	STRING_			(REV_CONTENT_MODEL, 32)
	STRING_			(REV_CONTENT_FORMAT, 64)
END_TABLE

TABLE_(PAGE)
	INT_			(PAGE_ID)			PRIMARY_KEY AUTO_INCREMENT
	INT_			(PAGE_NAMESPACE)
	INT_			(PAGE_HUB)			REFERENCES_(HUB, HUB_ID)
	STRING_			(PAGE_TITLE, 255)	DUAL_UNIQUE(PAGE_HUB, PAGE_TITLE)
	TINYBLOB_		(PAGE_RESTRICTIONS_ITEM)
	TINYINT_		(PAGE_IS_REDIRECT)
	TINYINT_		(PAGE_IS_NEW)
	DOUBLE_			(PAGE_RANDOM)
	TIME_			(PAGE_TOUCHED)
	TIME_			(PAGE_LINKS_UPDATED)
	INT64_			(PAGE_LATEST)		//REFERENCES_(REVISION, REV_ID)
	INT_			(PAGE_LEN)
	STRING_			(PAGE_CONTENT_MODEL, 32)
	STRING_			(PAGE_LANG, 35)
END_TABLE

TABLE_(REDIRECT)
	INT_			(RD_FROM)			REFERENCES_(PAGE, PAGE_ID)
	INT_			(RD_NAMESPACE)
	INT_			(RD_HUB)			REFERENCES_(HUB, HUB_ID)
	STRING_			(RD_TITLE, 255)
	STRING_			(RD_INTERHUB, 32)
	STRING_			(RD_FRAGMENT, 255)
END_TABLE

TABLE_(CATEGORY)
	INT_			(CAT_ID)			PRIMARY_KEY AUTO_INCREMENT
	STRING_			(CAT_TITLE, 255)
	INT_			(CAT_HUB)			REFERENCES_(HUB, HUB_ID) DUAL_UNIQUE(CAT_TITLE, CAT_HUB)
	INT_			(CAT_PAGES)
	INT_			(CAT_SUBCATS)
	INT_			(CAT_FILES)
END_TABLE

TABLE_(PAGE_PROPS)
	INT_			(PP_PAGE)			REFERENCES_(PAGE, PAGE_ID)
	STRING_			(PP_PROPNAME, 80)	DUAL_UNIQUE(PP_PAGE, PP_PROPNAME)
	BLOB_			(PP_VALUE)
	DOUBLE_			(PP_SORTKEY)
END_TABLE

TABLE_(PAGE_RESTRICTIONS)
	INT_			(PR_ID)				PRIMARY_KEY AUTO_INCREMENT
	INT_			(PR_PAGE)
	STRING_			(PR_TYPE, 60)
	STRING_			(PR_LEVEL, 60)
	TINYINT_		(PR_CASCADE)
	TIME_			(PR_EXPIRY)
END_TABLE

TABLE_(PROTECTED_TITLES)
	INT_			(PT_NAMESPACE)
	INT_			(PT_HUB)			REFERENCES_(HUB, HUB_ID)
	STRING_			(PT_TITLE, 255)		DUAL_UNIQUE(PT_HUB, PT_TITLE)
	INT_			(PT_USER)			REFERENCES_(USER, USER_ID)
	STRING_			(PT_REASON, 767)
	TIME_			(PT_TIMESTAMP)
	TIME_			(PT_EXPIRY)
	STRING_			(PT_CREATE_PERM, 60)
END_TABLE

TABLE_(PAGELINKS)
	INT_			(PL_FROM)			REFERENCES_(PAGE, PAGE_ID)
	INT_			(PL_FROM_NAMESPACE)
	INT_			(PL_HUB)			REFERENCES_(HUB, HUB_ID)
	INT_			(PL_NAMESPACE)
	STRING_			(PL_TITLE, 255)
END_TABLE

TABLE_(IWLINKS)
	INT_			(IWL_FROM)			REFERENCES_(PAGE, PAGE_ID)
	INT_			(IWL_FROM_HUB)		REFERENCES_(HUB, HUB_ID)
	INT_			(IWL_TO_HUB)		REFERENCES_(HUB, HUB_ID)
	STRING_			(IWL_TITLE, 255)
END_TABLE

TABLE_(EXTERNALLINKS)
	INT_			(EL_ID)				PRIMARY_KEY AUTO_INCREMENT
	INT_			(EL_FROM)			REFERENCES_(PAGE, PAGE_ID)
	INT_			(EL_HUB)			REFERENCES_(HUB, HUB_ID)
	BLOB_			(EL_TO)
	BLOB_			(EL_INDEX)
END_TABLE

TABLE_(LANGLINKS)
	INT_			(LL_FROM)			REFERENCES_(PAGE, PAGE_ID)
	INT_			(LL_HUB)			REFERENCES_(HUB, HUB_ID)
	STRING_			(LL_LANG, 20)
	STRING_			(LL_TITLE, 255)
END_TABLE

TABLE_(FILELINKS)
	INT_			(IL_FROM)			REFERENCES_(PAGE, PAGE_ID)
	INT_			(IL_FROM_NAMESPACE)
	INT_			(IL_FROM_HUB)		REFERENCES_(HUB, HUB_ID)
	STRING_			(IL_TO, 255)
END_TABLE

TABLE_(TEMPLATELINKS)
	INT_			(TL_FROM)			REFERENCES_(PAGE, PAGE_ID)
	INT_			(TL_FROM_NAMESPACE)
	INT_			(TL_FROM_HUB)		REFERENCES_(HUB, HUB_ID)
	INT_			(TL_NAMESPACE)
	STRING_			(TL_TITLE, 255)
END_TABLE

TABLE_(CATEGORYLINKS)
	INT_			(CL_FROM)			REFERENCES_(PAGE, PAGE_ID)
	INT_			(CL_HUB)			REFERENCES_(HUB, HUB_ID)
	STRING_			(CL_TO, 255)
	STRING_			(CL_SORTKEY, 230)
	STRING_			(CL_SORTKEY_PREFIX, 255)
	TIME_			(CL_TIMESTAMP)
	STRING_			(CL_COLLATION, 32)
	TINYINT_		(CL_TYPE)
END_TABLE

TABLE_(FILE_)
	INT_			(FILE_HUB)
	STRING_			(FILE_NAME, 255)	DUAL_UNIQUE(FILE_HUB, FILE_NAME)
	INT_			(FILE_SIZE)
	INT_			(FILE_WIDTH)
	INT_			(FILE_HEIGHT)
	MEDIUMBLOB_		(FILE_METADATA)
	INT_			(FILE_BITS)
	INT_			(FILE_MEDIA_TYPE)
	INT_			(FILE_MAJOR_MIME)
	STRING_			(FILE_MINOR_MIME, 100)
	STRING_			(FILE_DESCRIPTION, 767)
	INT_			(FILE_USER)			REFERENCES_(USER, USER_ID)
	STRING_			(FILE_USER_TEXT, 255)
	TIME_			(FILE_TIMESTAMP)
	STRING_			(FILE_MD5, 32)
END_TABLE

TABLE_(FILEARCHIVE)
	INT_			(FA_ID)				PRIMARY_KEY AUTO_INCREMENT
	INT_			(FA_HUB)
	STRING_			(FA_NAME, 255)
	STRING_			(FA_ARCHIVE_NAME, 255)	UNIQUE
	STRING_			(FA_STORAGE_GROUP, 16)
	STRING_			(FA_STORAGE_KEY, 64)
	INT_			(FA_DELETED_USER)	REFERENCES_(USER, USER_ID)
	TIME_			(FA_DELETED_TIMESTAMP)
	STRING_			(FA_DELETED_REASON, 767)
	INT_			(FA_SIZE)
	INT_			(FA_WIDTH)
	INT_			(FA_HEIGHT)
	MEDIUMBLOB_		(FA_METADATA)
	INT_			(FA_BITS)
	INT_			(FA_MEDIA_TYPE)
	INT_			(FA_MAJOR_MIME)
	STRING_			(FA_MINOR_MIME, 100)
	STRING_			(FA_DESCRIPTION, 767)
	INT_			(FA_USER)			REFERENCES_(USER, USER_ID)
	STRING_			(FA_USER_TEXT, 255)
	TIME_			(FA_TIMESTAMP)
	TINYINT_		(FA_DELETED)
	STRING_			(FA_MD5, 32)
END_TABLE

TABLE_(UPLOADSTASH)
	INT_			(US_ID)				PRIMARY_KEY AUTO_INCREMENT
	INT_			(US_USER)			REFERENCES_(USER, USER_ID)
	STRING_			(US_KEY, 255)		UNIQUE
	STRING_			(US_ORIG_PATH, 255)
	STRING_			(US_PATH, 255)
	STRING_			(US_SOURCE_TYPE, 50)
	TIME_			(US_TIMESTAMP)
	STRING_			(US_STATUS, 50)
	INT_			(US_CHUNK_INX)
	BLOB_			(US_PROPS)
	INT_			(US_SIZE)
	STRING_			(US_MD5, 32)
	STRING_			(US_MIME, 255)
	INT_			(US_MEDIA_TYPE)
	INT_			(US_IMAGE_WIDTH)
	INT_			(US_IMAGE_HEIGHT)
	INT_			(US_IMAGE_BITS)
END_TABLE

TABLE_(JOB)
	INT_			(JOB_ID)			PRIMARY_KEY AUTO_INCREMENT
	STRING_			(JOB_CMD, 60)
	INT_			(JOB_NAMESPACE)
	INT_			(JOB_HUB)			REFERENCES_(HUB, HUB_ID)
	STRING_			(JOB_TITLE, 255)
	TIME_			(JOB_TIMESTAMP)
	BLOB_			(JOB_PARAMS)
	INT_			(JOB_RANDOM)
	INT_			(JOB_ATTEMPTS)
	STRING_			(JOB_TOKEN, 32)
	TIME_			(JOB_TOKEN_TIMESTAMP)
	STRING_			(JOB_MD5, 32)
END_TABLE

TABLE_(SITE_STATS)
	INT_			(SS_ID)				PRIMARY_KEY AUTO_INCREMENT
	INT64_			(SS_TOTAL_EDITS)
	INT64_			(SS_GOOD_ARTICLES)
	INT64_			(SS_TOTAL_PAGES)
	INT64_			(SS_USERS)
	INT64_			(SS_ACTIVE_USERS)
	INT64_			(SS_FILES)
	INT_			(SS_HUBS)
	TIME_			(SS_TIMESTAMP)
END_TABLE

TABLE_(SEARCHINDEX)
	INT_			(SI_PAGE)			REFERENCES_(PAGE, PAGE_ID) UNIQUE
	INT_			(SI_HUB)			REFERENCES_(HUB, HUB_ID)
	STRING_			(SI_TITLE, 255)
	MEDIUMBLOB_		(SI_TEXT)
END_TABLE

TABLE_(WIKIPEDIA)
	STRING_			(WP_PREFIX, 10)
	STRING_			(WP_TITLE, 255)			DUAL_UNIQUE(WP_PREFIX, WP_TITLE)
	TIME_			(WP_EXPIRY)
	INT64_			(WP_TEXT_ID)
END_TABLE

TABLE_(TEXT)
	INT64_			(TEXT_COUNT)
END_TABLE
