#ifndef _Local_Ctrl_h_
#define _Local_Ctrl_h_


NAMESPACE_TOPSIDE_BEGIN


#ifdef flagGUI

enum EventStateKey {
	KEYBOARD_PRESSED,
	KEYBOARD_STATE_ITER,
	
	SCREEN0_SIZE,
	SCREEN0_OFFSET,
	
	
	MOUSE_EVENT_BASE = 0x1000,
	
	#define MOUSE_EVENT(x) MOUSE_##x = MOUSE_EVENT_BASE + Ctrl::x,
	
	MOUSE_EVENT(BUTTON)
	MOUSE_EVENT(ACTION)

	MOUSE_EVENT(MOUSEENTER)
	MOUSE_EVENT(MOUSEMOVE)
	MOUSE_EVENT(MOUSELEAVE)
	MOUSE_EVENT(CURSORIMAGE)
	MOUSE_EVENT(MOUSEWHEEL)

	MOUSE_EVENT(DOWN)
	MOUSE_EVENT(UP)
	MOUSE_EVENT(DOUBLE)
	MOUSE_EVENT(REPEAT)
	MOUSE_EVENT(DRAG)
	MOUSE_EVENT(HOLD)
	MOUSE_EVENT(TRIPLE)
	MOUSE_EVENT(PEN)
	MOUSE_EVENT(PENLEAVE)

	MOUSE_EVENT(LEFTDOWN)
	MOUSE_EVENT(LEFTDOUBLE)
	MOUSE_EVENT(LEFTREPEAT)
	MOUSE_EVENT(LEFTUP)
	MOUSE_EVENT(LEFTDRAG)
	MOUSE_EVENT(LEFTHOLD)
	MOUSE_EVENT(LEFTTRIPLE)

	MOUSE_EVENT(MIDDLEDOWN)
	MOUSE_EVENT(MIDDLEDOUBLE)
	MOUSE_EVENT(MIDDLEREPEAT)
	MOUSE_EVENT(MIDDLEUP)
	MOUSE_EVENT(MIDDLEDRAG)
	MOUSE_EVENT(MIDDLEHOLD)
	MOUSE_EVENT(MIDDLETRIPLE)
	
	MOUSE_EVENT(RIGHTDOWN)
	MOUSE_EVENT(RIGHTDOUBLE)
	MOUSE_EVENT(RIGHTREPEAT)
	MOUSE_EVENT(RIGHTUP)
	MOUSE_EVENT(RIGHTDRAG)
	MOUSE_EVENT(RIGHTHOLD)
	MOUSE_EVENT(RIGHTTRIPLE)
	
	#undef MOUSE_EVENT
	
	MOUSE_EVENT_END = 0x1FFF,
	
	MOUSE_TOYCOMPAT_DRAG,
	MOUSE_TOYCOMPAT_CLICK,
	
};

#endif



NAMESPACE_TOPSIDE_END

#endif
