#ifndef _ParallelMach_Generated_h_
#define _ParallelMach_Generated_h_

// This file is generated. Do not modify this file.

namespace TS {

namespace Parallel {

#define ATOM_TYPE_LIST \
	ATOM_TYPE(CENTER_CUSTOMER) \
	ATOM_TYPE(TEST_REALTIME_SRC) \
	ATOM_TYPE(TEST_REALTIME_SINK) \
	ATOM_TYPE(TEST_POLLER_SINK) \
	ATOM_TYPE(PORTAUDIO_SINK) \
	ATOM_TYPE(AUDIO_DBG_SRC) \
	ATOM_TYPE(AUDIO_SPLITTER) \
	ATOM_TYPE(AUDIO_SPLITTER_USER) \
	ATOM_TYPE(AUDIO_JOINER) \
	ATOM_TYPE(AUDIO_JOINER_USER) \
	ATOM_TYPE(AUDIO_JOINER2_USER) \
	ATOM_TYPE(REMOTE_V_R_SERVER_PIPE) \
	ATOM_TYPE(BLUETOOTH_HOLO_PIPE) \
	ATOM_TYPE(TEST_EVENT_SRC_PIPE) \
	ATOM_TYPE(VOLUME_LOADER_ATOM) \


#define ATOM_CLASS_LIST \
	ATOM_CLASS(CenterCustomer) \
	ATOM_CLASS(TestRealtimeSrc) \
	ATOM_CLASS(TestRealtimeSink) \
	ATOM_CLASS(TestPollerSink) \
	ATOM_CLASS(PortaudioSink) \
	ATOM_CLASS(AudioDbgSrc) \
	ATOM_CLASS(AudioSplitter) \
	ATOM_CLASS(AudioSplitterUser) \
	ATOM_CLASS(AudioJoiner) \
	ATOM_CLASS(AudioJoinerUser) \
	ATOM_CLASS(AudioJoiner2User) \
	ATOM_CLASS(RemoteVRServerPipe) \
	ATOM_CLASS(BluetoothHoloPipe) \
	ATOM_CLASS(TestEventSrcPipe) \
	ATOM_CLASS(VolumeLoaderAtom) \


#define flagFFMPEG_ATOM_TYPE_LIST \
	ATOM_TYPE(AUDIO_DECODER_SRC) \
	ATOM_TYPE(AUDIO_LOADER_ATOM) \
	ATOM_TYPE(VIDEO_LOADER_ATOM) \


#define flagFFMPEG_ATOM_CLASS_LIST \
	ATOM_CLASS(AudioDecoderSrc) \
	ATOM_CLASS(AudioLoaderAtom) \
	ATOM_CLASS(VideoLoaderAtom) \


#define flagSCREEN_ATOM_TYPE_LIST \
	ATOM_TYPE(VIDEO_DBG_SRC) \
	ATOM_TYPE(EVENT_STATE_PIPE) \
	ATOM_TYPE(ECS_PROG_VIDEO) \
	ATOM_TYPE(X11_SW_FBO_PROG) \
	ATOM_TYPE(X11_SW_SHADER_PIPE) \
	ATOM_TYPE(X11_SW_FBO_ATOM_PIPE) \
	ATOM_TYPE(X11_CONTEXT_ATOM) \
	ATOM_TYPE(X11_EVENT_ATOM_PIPE) \
	ATOM_TYPE(OGL_CUSTOMER) \
	ATOM_TYPE(X11_VIDEO_ATOM_PIPE) \
	ATOM_TYPE(X11_SW_VIDEO_ATOM_PIPE) \
	ATOM_TYPE(X11_SW_FBO_ATOM_S_A) \


#define flagSCREEN_ATOM_CLASS_LIST \
	ATOM_CLASS(VideoDbgSrc) \
	ATOM_CLASS(EventStatePipe) \
	ATOM_CLASS(EcsProgVideo) \
	ATOM_CLASS(X11SwFboProg) \
	ATOM_CLASS(X11SwShaderPipe) \
	ATOM_CLASS(X11SwFboAtomPipe) \
	ATOM_CLASS(X11ContextAtom) \
	ATOM_CLASS(X11EventAtomPipe) \
	ATOM_CLASS(OglCustomer) \
	ATOM_CLASS(X11VideoAtomPipe) \
	ATOM_CLASS(X11SwVideoAtomPipe) \
	ATOM_CLASS(X11SwFboAtomSA) \


#define flagOPENCV_ATOM_TYPE_LIST \


#define flagOPENCV_ATOM_CLASS_LIST \


#define flagLINUX_ATOM_TYPE_LIST \
	ATOM_TYPE(WEBCAM_PIPE) \
	ATOM_TYPE(WEBCAM_ATOM) \


#define flagLINUX_ATOM_CLASS_LIST \
	ATOM_CLASS(WebcamPipe) \
	ATOM_CLASS(WebcamAtom) \


#define flagOGL_ATOM_TYPE_LIST \
	ATOM_TYPE(X11_OGL_FBO_PROG) \
	ATOM_TYPE(X11_OGL_SHADER_PIPE) \
	ATOM_TYPE(X11_OGL_FBO_ATOM_PIPE) \
	ATOM_TYPE(SDL_OGL_IMAGE_LOADER) \
	ATOM_TYPE(X11_OGL_VIDEO_ATOM_PIPE) \
	ATOM_TYPE(X11_OGL_FBO_ATOM_S_A) \
	ATOM_TYPE(SDL_OGL_FBO_ATOM_S_A) \
	ATOM_TYPE(SDL_OGL_FBO_PIPE) \
	ATOM_TYPE(SDL_OGL_FBO_ATOM) \
	ATOM_TYPE(SDL_OGL_SHADER_ATOM) \
	ATOM_TYPE(SDL_OGL_SHADER_ATOM_S_A) \
	ATOM_TYPE(SDL_OGL_TEXTURE_SOURCE) \
	ATOM_TYPE(SDL_OGL_VOLUME_SOURCE) \
	ATOM_TYPE(SDL_OGL_AUDIO_SINK) \
	ATOM_TYPE(SDL_OGL_KEYBOARD_SOURCE) \
	ATOM_TYPE(SDL_OGL_AUDIO_SOURCE) \


#define flagOGL_ATOM_CLASS_LIST \
	ATOM_CLASS(X11OglFboProg) \
	ATOM_CLASS(X11OglShaderPipe) \
	ATOM_CLASS(X11OglFboAtomPipe) \
	ATOM_CLASS(SdlOglImageLoader) \
	ATOM_CLASS(X11OglVideoAtomPipe) \
	ATOM_CLASS(X11OglFboAtomSA) \
	ATOM_CLASS(SdlOglFboAtomSA) \
	ATOM_CLASS(SdlOglFboPipe) \
	ATOM_CLASS(SdlOglFboAtom) \
	ATOM_CLASS(SdlOglShaderAtom) \
	ATOM_CLASS(SdlOglShaderAtomSA) \
	ATOM_CLASS(SdlOglTextureSource) \
	ATOM_CLASS(SdlOglVolumeSource) \
	ATOM_CLASS(SdlOglAudioSink) \
	ATOM_CLASS(SdlOglKeyboardSource) \
	ATOM_CLASS(SdlOglAudioSource) \


#define flagSDL2_ATOM_TYPE_LIST \
	ATOM_TYPE(SDL_OGL_FBO_PROG) \
	ATOM_TYPE(SDL_OGL_SHADER_PIPE) \
	ATOM_TYPE(SDL_OGL_FBO_ATOM_PIPE) \
	ATOM_TYPE(SDL_CONTEXT_ATOM) \
	ATOM_TYPE(SDL_EVENT_ATOM_PIPE) \
	ATOM_TYPE(SDL_VIDEO_ATOM_PIPE) \
	ATOM_TYPE(SDL_PROG_ATOM_PIPE) \
	ATOM_TYPE(SDL_VIDEO_ATOM) \
	ATOM_TYPE(SDL_AUDIO_ATOM) \


#define flagSDL2_ATOM_CLASS_LIST \
	ATOM_CLASS(SdlOglFboProg) \
	ATOM_CLASS(SdlOglShaderPipe) \
	ATOM_CLASS(SdlOglFboAtomPipe) \
	ATOM_CLASS(SdlContextAtom) \
	ATOM_CLASS(SdlEventAtomPipe) \
	ATOM_CLASS(SdlVideoAtomPipe) \
	ATOM_CLASS(SdlProgAtomPipe) \
	ATOM_CLASS(SdlVideoAtom) \
	ATOM_CLASS(SdlAudioAtom) \


#define flagOPENHMD_ATOM_TYPE_LIST \
	ATOM_TYPE(OPEN_H_M_D_PIPE) \


#define flagOPENHMD_ATOM_CLASS_LIST \
	ATOM_CLASS(OpenHMDPipe) \


#define flagLOCALHMD_ATOM_TYPE_LIST \
	ATOM_TYPE(LOCAL_H_M_D_PIPE) \


#define flagLOCALHMD_ATOM_CLASS_LIST \
	ATOM_CLASS(LocalHMDPipe) \


#define flagVR_ATOM_TYPE_LIST \
	ATOM_TYPE(SPATIAL_INTERACTION_S_A) \


#define flagVR_ATOM_CLASS_LIST \
	ATOM_CLASS(SpatialInteractionSA) \


}

}



#endif
